///////////////////////////////////////////////////////////
//  CalendarConnector.cs
//  Implementation of the Component Calendar-Connector
//  Generated by Enterprise Architect
//  Created on:      04-Mai-2021 10:50:02
//  Original author: mkaul
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

namespace CalendarHeatingRoomPlanningUI
{
    public class CalendarConnector : SettingsSubscriber, CalendarPublisher
    {
        /// <summary>
        /// Used for lazy initialization
        /// </summary>
        private static readonly Lazy<CalendarConnector>
                lazy = new Lazy<CalendarConnector>(() => new CalendarConnector());

        /// <summary>
        /// Used to access the singleton
        /// </summary>
        public static CalendarConnector Instance { get { return lazy.Value; } }

        /// <summary>
        /// Destination of all calendar data read from the URL
        /// </summary>
        public Ical.Net.Calendar Calendar { get; set; }

        /// <summary>
        /// URL to the calendar webcal site - will be updated by the SettingsManager via its publisher feature.
        /// </summary>
        private string _ical_url;

        /// <summary>
        /// List of currently registered subscribers. At notify all these subscribers will be called via their Update() operation.
        /// </summary>
        private List<CalendarSubscriber> Subscribers { get; set; }

        /// <summary>
        /// Temporary used data
        /// ToDo: can be removed in production version
        /// </summary>
        public List<string> Data { get; set; }

        private CalendarConnector()
        {
            Subscribers = new List<CalendarSubscriber>();
            Data = new List<string>();

            SettingsManager.Instance.Attach(this);
            _ical_url = SettingsManager.Instance.Settings.Calendar.ICalUrl;
        }

        ~CalendarConnector()
        {
            SettingsManager.Instance.Detach(this);
        }

        /// <summary>
        /// Registers new subscriber to the list of subscribers - when notify is called
        /// then all currently registered subscribers are called.
        /// </summary>
        /// <param name="subscriber"></param>
        public void Attach(CalendarSubscriber subscriber)
        {
            if (!Subscribers.Contains(subscriber))
            {
                Subscribers.Add(subscriber);
            }
        }

        /// <summary>
        /// Removes the subscriber from the list of subscribers - when notify is called
        /// then all currently registered subscribers are called.
        /// </summary>
        /// <param name="subscriber"></param>
        public void Detach(CalendarSubscriber subscriber)
        {
            if (Subscribers.Contains(subscriber))
            {
                Subscribers.Remove(subscriber);
            }
        }

        /// <summary>
        /// For all registered subscribers their Update() operation is called - used to
        /// notify the subscribers. This notify will be published to the subscribers when
        /// calendar data was fetched.
        /// </summary>
        public void Notify()
        {
			foreach(CalendarSubscriber subscriber in Subscribers)
            {
				subscriber.Update(this);
            }
        }

        /// <summary>
        /// This operation will be called when the publisher notifies new setting data.
        /// </summary>
        /// <param name="publisher"></param>
        public void Update(SettingsPublisher publisher)
        {
            _ical_url = SettingsManager.Instance.Settings.Calendar.ICalUrl;
        }

        /// <summary>
        /// Reads the calendar data from the via settings manager specified iCal WebSite.
        /// </summary>
        public void FetchCalendarData()
        {
            try
            {
                if(Calendar != null)
                {
                    Calendar = null;
                }

                // load data from webcal URl
                System.Net.WebClient client = new System.Net.WebClient();
                // validate url
                if ((_ical_url.Length > 0) && (_ical_url.ToLower().StartsWith("http")))
                {
                    System.IO.Stream stream = client.OpenRead(_ical_url);
                    // System.IO.FileStream stream = new System.IO.FileStream("C:\\Temp\\calendar.ics", System.IO.FileMode.Open, System.IO.FileAccess.Read);
                    System.IO.StreamReader reader = new System.IO.StreamReader(stream);
                    string iCalData = reader.ReadToEnd();
                    string iCalDataNoComments = "";

                    // remove comment -> not processed by ical library
                    using (var iCalDataReader = new System.IO.StringReader(iCalData))
                    {
                        for (string line = iCalDataReader.ReadLine(); line != null; line = iCalDataReader.ReadLine())
                        {
                            if (line.Length == 0) continue;
                            if (line[0] != '/')
                            {
                                iCalDataNoComments += line + System.Environment.NewLine;
                            }
                        }
                    }
                    // let parse data from ical calendar            
                    Calendar = Ical.Net.Calendar.Load(iCalDataNoComments);

                    foreach (Ical.Net.CalendarComponents.CalendarEvent cal in Calendar.Children)
                    {
                        Data.Add("test");
                    }
                }

                // publish new data
                Notify();
            }
            finally
            {
            }
        }
    }
}