///////////////////////////////////////////////////////////
//  HeatingCalculation.cs
//  Implementation of the Component Heating Calculation
//  Generated by Enterprise Architect
//  Created on:      04-Mai-2021 20:30:38
//  Original author: mkaul
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using CalendarHeatingRoomPlanning;

namespace CalendarHeatingRoomPlanningUI
{
    /// <summary>
    /// Uses the fetched calendar events data and analyzes it. It scans the events, checks what 
    /// rooms are in the events and calculates the heating plan for each room.
    /// </summary>
    public class HeatingCalculation : SettingsSubscriber, CalendarSubscriber
    {

        public HeatingCalculation()
        {
            SettingsManager.Instance.Attach(this);
            CalendarConnector.Instance.Attach(this);
        }

        ~HeatingCalculation()
        {
            SettingsManager.Instance.Detach(this);
            CalendarConnector.Instance.Detach(this);
        }

        /// <summary>
        /// This operation will be called when the publisher notifies new setting data.
        /// </summary>
        /// <param name="publisher"></param>
        public void Update(SettingsPublisher publisher)
        {
        }

        /// <summary>
        /// This operation will be called when the publisher notifies new fetched calendar
        /// data.
        /// </summary>
        /// <param name="publisher"></param>
        public void Update(CalendarPublisher publisher)
        {
        }
    }
}