///////////////////////////////////////////////////////////
//  Settings-Publisher.cs
//  Implementation of the Interface Settings-Publisher
//  Generated by Enterprise Architect
//  Created on:      03-Mai-2021 19:24:12
//  Original author: mkaul
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

namespace CalendarHeatingRoomPlanningUI
{
	/// <summary>
	/// This interface class specify the operations of the settings publisher. The
	/// settings publisher will publish changed settings to all registered subscribers.
	/// 
	/// </summary>
	public interface SettingsPublisher  
	{
		/// <summary>
		/// Registers new subscriber to the list of subscribers - when notify is called
		/// then all currently registered subscribers are called.
		/// </summary>
		/// <param name="subscriber"></param>
		void Attach(SettingsSubscriber subscriber);

		/// <summary>
		/// Removes the subscriber from the list of subscribers - when notify is called
		/// then all currently registered subscribers are called.
		/// </summary>
		/// <param name="subscriber"></param>
		void Detach(SettingsSubscriber subscriber);

		/// <summary>
		/// For all registered subscribers their Update() operation is called - used to
		/// notify the subscribers. This notify will be published to the subscribers when
		/// the settings where changed.
		/// </summary>
		void Notify();
	}
}