//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace CalendarHeatingRoomPlanning {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.exampleURI.com/Schema1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.exampleURI.com/Schema1", IsNullable=false)]
    public partial class CalendarDataModel {
        //??PATCHED martin@familie-kaul.de 2021-05-04: use List collection instead of Array
        private System.Collections.Generic.List<SingleEvent> eventDataField;

        /// <remarks/>
        //??PATCHED martin@familie-kaul.de 2021-05-04: use List collection instead of Array
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Events", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public System.Collections.Generic.List<SingleEvent> EventData {
            get {
                return this.eventDataField;
            }
            set {
                this.eventDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.exampleURI.com/Schema1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.exampleURI.com/Schema1", IsNullable=false)]
    public partial class SingleEvent {
        
        private bool dayEventField;
        
        private bool dayEventFieldSpecified;
        
        private string descriptionField;
        
        private System.DateTime startField;
        
        private bool startFieldSpecified;
        
        private System.DateTime stopField;
        
        private bool stopFieldSpecified;
        
        public SingleEvent() {
            this.dayEventField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool DayEvent {
            get {
                return this.dayEventField;
            }
            set {
                this.dayEventField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DayEventSpecified {
            get {
                return this.dayEventFieldSpecified;
            }
            set {
                this.dayEventFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime Start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StartSpecified {
            get {
                return this.startFieldSpecified;
            }
            set {
                this.startFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime Stop {
            get {
                return this.stopField;
            }
            set {
                this.stopField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StopSpecified {
            get {
                return this.stopFieldSpecified;
            }
            set {
                this.stopFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.exampleURI.com/Schema1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.exampleURI.com/Schema1", IsNullable=false)]
    public partial class Events {

        //??PATCHED martin@familie-kaul.de 2021-05-04: use List collection instead of Array
        private System.Collections.Generic.List<SingleEvent> events1Field;

        /// <remarks/>
        //??PATCHED martin@familie-kaul.de 2021-05-04: use List collection instead of Array
        [System.Xml.Serialization.XmlElementAttribute("Events", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.Generic.List<SingleEvent> Events1 {
            get {
                return this.events1Field;
            }
            set {
                this.events1Field = value;
            }
        }
    }
}
